from django.urls import path

from .views import (
    ArtistCreateView,
    ArtistDeleteView,
    ArtistListView,
    ArtistRecordCreateView,
    ArtistRecordDeleteView,
    ArtistRecordListView,
    ArtistRecordUpdateView,
    ArtistUpdateView,
    GroupingCreateView,
    GroupingListView,
    GroupingRecordBatchUpdateView,
    GroupingRecordBatchCreateView,
    GroupingRecordBatchDeleteView,
    GroupingRecordBatchDetailView,
    GroupingRecordBatchProcessStandbyView,
    GroupingRecordListView,
    GroupingUpdateView,
    CalculatorView,
    agrupacion_artistas,
    artist_bulk_upload_view,
    calcular_costes_agrupacion,
    calcular_costes_desde_neto,
    calcular_costes_por_tramo,
)

app_name = "artists"

urlpatterns = [
    path("", ArtistListView.as_view(), name="list"),
    path("calculadora/", CalculatorView.as_view(), name="calculator"),
    path("registros/", ArtistRecordListView.as_view(), name="record-list"),
    path("registros/agrupaciones/", GroupingRecordListView.as_view(), name="record-grouping-list"),
    path(
        "registros/agrupaciones/<int:pk>/",
        GroupingRecordBatchDetailView.as_view(),
        name="record-grouping-detail",
    ),
    path("registros/agrupaciones/<int:pk>/edit/", GroupingRecordBatchUpdateView.as_view(), name="record-grouping-update"),
    path(
        "registros/agrupaciones/<int:pk>/delete/",
        GroupingRecordBatchDeleteView.as_view(),
        name="record-grouping-delete",
    ),
    path(
        "registros/agrupaciones/standby/<int:pk>/procesar/",
        GroupingRecordBatchProcessStandbyView.as_view(),
        name="record-grouping-standby-process",
    ),
    path("api/calcular-costes/", calcular_costes_por_tramo, name="calcular-costes"),
    path("api/calcular-costes-desde-neto/", calcular_costes_desde_neto, name="calcular-costes-desde-neto"),
    path("api/calcular-costes-agrupacion/", calcular_costes_agrupacion, name="calcular-costes-agrupacion"),
    path("api/agrupacion-artistas/", agrupacion_artistas, name="agrupacion-artistas"),
    path("agrupaciones/", GroupingListView.as_view(), name="grouping-list"),
    path("agrupaciones/registros/nuevo/", GroupingRecordBatchCreateView.as_view(), name="grouping-record-create"),
    path("agrupaciones/nueva/", GroupingCreateView.as_view(), name="grouping-create"),
    path("agrupaciones/<int:pk>/editar/", GroupingUpdateView.as_view(), name="grouping-update"),
    path("new/", ArtistCreateView.as_view(), name="create"),
    path("bulk-upload/", artist_bulk_upload_view, name="bulk-upload"),
    path("registros/new/", ArtistRecordCreateView.as_view(), name="record-create"),
    path("registros/<int:pk>/edit/", ArtistRecordUpdateView.as_view(), name="record-update"),
    path("registros/<int:pk>/delete/", ArtistRecordDeleteView.as_view(), name="record-delete"),
    path("<int:pk>/edit/", ArtistUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", ArtistDeleteView.as_view(), name="delete"),
]
