# Generated by Django 4.2.16 on 2026-06-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agrupación',
                'verbose_name_plural': 'Agrupaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dni_nie', models.CharField(max_length=20, unique=True)),
                ('bank_account', models.CharField(blank=True, max_length=34)),
                ('social_security_number', models.CharField(max_length=30)),
                ('is_autonomous', models.BooleanField(default=False)),
                ('irpf_type', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('date_high', models.DateField()),
                ('date_low', models.DateField(blank=True, null=True)),
                ('a1_request', models.BooleanField(default=False)),
                ('cancelled_process', models.BooleanField(default=False)),
                ('registration_type', models.CharField(choices=[('SOLO', 'Solista'), ('BAND', 'Banda')], default='SOLO', max_length=10)),
                ('cache_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('management_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('social_security_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irpf_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'Pagado'), ('PENDING_INVOICE', 'Pendiente Factura'), ('IN_PROGRESS', 'En Proceso'), ('PARTIAL', 'Pago a Medias'), ('CANCELLED', 'Anulado')], default='IN_PROGRESS', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grouping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='artists.grouping')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['full_name'],
            },
        ),
    ]
