# Generated by Django 4.2.16 on 2026-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_number', models.PositiveIntegerField(help_text='Número de tramo (1-4)', unique=True)),
                ('min_range', models.DecimalField(decimal_places=2, help_text='Rango mínimo', max_digits=10)),
                ('max_range', models.DecimalField(decimal_places=2, help_text='Rango máximo', max_digits=10)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base para cálculo (dejar vacío para tramo 1)', max_digits=10, null=True)),
                ('company_percentage', models.DecimalField(decimal_places=2, help_text='% Costo empresa', max_digits=5)),
                ('management_percentage', models.DecimalField(decimal_places=2, help_text='% Costo gestión', max_digits=5)),
                ('social_security_percentage', models.DecimalField(decimal_places=2, help_text='% Seguridad Social', max_digits=5)),
                ('irpf_percentage', models.DecimalField(decimal_places=2, help_text='% IRPF', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tramo de Precios',
                'verbose_name_plural': 'Tramos de Precios',
                'ordering': ['bracket_number'],
            },
        ),
    ]
