from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_pricebracket"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="grouping",
            table="agrupaciones",
        ),
        migrations.RenameField(
            model_name="grouping",
            old_name="name",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="grouping",
            old_name="description",
            new_name="descripcion",
        ),
        migrations.RenameField(
            model_name="grouping",
            old_name="active",
            new_name="activo",
        ),
        migrations.RenameField(
            model_name="grouping",
            old_name="created_at",
            new_name="creado_en",
        ),
        migrations.AlterModelOptions(
            name="grouping",
            options={"ordering": ["nombre"], "verbose_name": "Agrupación", "verbose_name_plural": "Agrupaciones"},
        ),
        migrations.AlterModelTable(
            name="artist",
            table="artistas",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="full_name",
            new_name="nombre_completo",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="bank_account",
            new_name="cuenta_bancaria",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="social_security_number",
            new_name="numero_seguridad_social",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="is_autonomous",
            new_name="es_autonomo",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="irpf_type",
            new_name="tipo_irpf",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="date_high",
            new_name="fecha_alta",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="date_low",
            new_name="fecha_baja",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="a1_request",
            new_name="solicitud_a1",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="cancelled_process",
            new_name="proceso_cancelado",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="registration_type",
            new_name="tipo_registro",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="grouping",
            new_name="agrupacion",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="cache_net",
            new_name="cache_neto",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="company_cost",
            new_name="coste_empresa",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="management_cost",
            new_name="coste_gestion",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="social_security_cost",
            new_name="coste_seguridad_social",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="irpf_cost",
            new_name="coste_irpf",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="payment_status",
            new_name="estado_pago",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="observations",
            new_name="observaciones",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="created_at",
            new_name="creado_en",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="updated_at",
            new_name="actualizado_en",
        ),
        migrations.AlterField(
            model_name="artist",
            name="agrupacion",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artistas", to="artists.grouping"),
        ),
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["nombre_completo"], "verbose_name": "Artista", "verbose_name_plural": "Artistas"},
        ),
        migrations.AlterModelTable(
            name="pricebracket",
            table="tramos_precios",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="bracket_number",
            new_name="numero_tramo",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="min_range",
            new_name="rango_minimo",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="max_range",
            new_name="rango_maximo",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="base_amount",
            new_name="importe_base",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="company_percentage",
            new_name="porcentaje_empresa",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="management_percentage",
            new_name="porcentaje_gestion",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="social_security_percentage",
            new_name="porcentaje_seguridad_social",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="irpf_percentage",
            new_name="porcentaje_irpf",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="active",
            new_name="activo",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="created_at",
            new_name="creado_en",
        ),
        migrations.RenameField(
            model_name="pricebracket",
            old_name="updated_at",
            new_name="actualizado_en",
        ),
        migrations.AlterModelOptions(
            name="pricebracket",
            options={"ordering": ["numero_tramo"], "verbose_name": "Tramo de Precios", "verbose_name_plural": "Tramos de Precios"},
        ),
    ]
