# Generated by Django 4.2.16 on 2026-06-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_grouping_artistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistrecord',
            name='estado_pago',
            field=models.CharField(choices=[('PAID', 'Pagado'), ('PENDING_INVOICE', 'Pendiente pago'), ('IN_PROGRESS', 'En Proceso'), ('PARTIAL', 'Pago a Medias'), ('CANCELLED', 'Anulado')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='artistrecord',
            name='solicitud_a1',
            field=models.BooleanField(default=False, verbose_name='Solicitud A1'),
        ),
    ]
