# Generated by Django 4.2.16 on 2026-06-15 10:49

from django.db import migrations, models
import django.db.models.deletion


def set_group_from_existing_associations(apps, schema_editor):
    Artist = apps.get_model("artists", "Artist")

    for artist in Artist.objects.all().iterator():
        first_group = artist.agrupaciones.order_by("id").first()
        if first_group:
            artist.grupo_asociado_id = first_group.id
            artist.save(update_fields=["grupo_asociado"])


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artistrecord_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='artist',
            name='grupo_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artistas_asociados', to='artists.grouping'),
        ),
        migrations.AddField(
            model_name='artist',
            name='irpf',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='artist',
            name='prl',
            field=models.BooleanField(default=False, verbose_name='PRL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(set_group_from_existing_associations, migrations.RunPython.noop),
    ]
