# Generated by Django 4.2.16 on 2026-06-15 00:00

from django.db import migrations


def sync_artist_fk_to_grouping_artistas(apps, schema_editor):
    Grouping = apps.get_model("artists", "Grouping")
    Artist = apps.get_model("artists", "Artist")

    for artist in Artist.objects.exclude(grupo_asociado__isnull=True).iterator():
        grouping = Grouping.objects.filter(id=artist.grupo_asociado_id).first()
        if grouping:
            grouping.artistas.add(artist)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0008_artist_email_artist_grupo_asociado_artist_irpf_and_more"),
    ]

    operations = [
        migrations.RunPython(sync_artist_fk_to_grouping_artistas, noop_reverse),
        migrations.RemoveField(model_name="artist", name="grupo_asociado"),
    ]
