# Generated by Django 4.2.16 on 2026-06-15 11:40

from django.db import migrations, models


def copy_percentages_to_global_settings(apps, schema_editor):
    PriceBracket = apps.get_model('artists', 'PriceBracket')
    CostPercentageSettings = apps.get_model('artists', 'CostPercentageSettings')

    source = PriceBracket.objects.order_by('numero_tramo', 'id').first()
    defaults = {
        'contingencias_comunes_empresa': 15,
        'contingencias_comunes_trabajador': 5,
        'mei_empresa': 0,
        'mei_trabajador': 0,
        'desempleo_empresa': 0,
        'desempleo_trabajador': 0,
        'formacion_empresa': 0,
        'formacion_trabajador': 0,
        'at_ep_empresa': 0,
        'fogasa_empresa': 0,
        'porcentaje_gestion': 10,
        'porcentaje_irpf': 8,
    }

    if source:
        defaults = {
            'contingencias_comunes_empresa': source.porcentaje_empresa,
            'contingencias_comunes_trabajador': source.porcentaje_seguridad_social,
            'mei_empresa': 0,
            'mei_trabajador': 0,
            'desempleo_empresa': 0,
            'desempleo_trabajador': 0,
            'formacion_empresa': 0,
            'formacion_trabajador': 0,
            'at_ep_empresa': 0,
            'fogasa_empresa': 0,
            'porcentaje_gestion': source.porcentaje_gestion,
            'porcentaje_irpf': source.porcentaje_irpf,
        }

    CostPercentageSettings.objects.update_or_create(id=1, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_sync_and_remove_grouping_artistas_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostPercentageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingencias_comunes_empresa', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Contingencias comunes empresa')),
                ('contingencias_comunes_trabajador', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Contingencias comunes trabajador')),
                ('mei_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='MEI empresa')),
                ('mei_trabajador', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='MEI trabajador')),
                ('desempleo_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desempleo empresa')),
                ('desempleo_trabajador', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desempleo trabajador')),
                ('formacion_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Formación empresa')),
                ('formacion_trabajador', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Formación trabajador')),
                ('at_ep_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='AT y EP empresa')),
                ('fogasa_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fondo de garantía salarial empresa')),
                ('porcentaje_gestion', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('porcentaje_irpf', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de porcentajes',
                'verbose_name_plural': 'Configuración de porcentajes',
                'db_table': 'configuracion_porcentajes',
            },
        ),
        migrations.RunPython(copy_percentages_to_global_settings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pricebracket',
            name='porcentaje_empresa',
        ),
        migrations.RemoveField(
            model_name='pricebracket',
            name='porcentaje_gestion',
        ),
        migrations.RemoveField(
            model_name='pricebracket',
            name='porcentaje_irpf',
        ),
        migrations.RemoveField(
            model_name='pricebracket',
            name='porcentaje_seguridad_social',
        ),
    ]
