# Generated by Django 4.2.16 on 2026-06-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_ensure_sectional_percentage_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='at_ep_empresa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='AT y EP empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='contingencias_comunes_empresa',
            field=models.DecimalField(decimal_places=4, default=15, max_digits=7, verbose_name='Contingencias comunes empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='contingencias_comunes_trabajador',
            field=models.DecimalField(decimal_places=4, default=5, max_digits=7, verbose_name='Contingencias comunes trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='desempleo_empresa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Desempleo empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='desempleo_trabajador',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Desempleo trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='fogasa_empresa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Fondo de garantía salarial empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='formacion_empresa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Formación empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='formacion_trabajador',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Formación trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='mei_empresa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='MEI empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='mei_trabajador',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='MEI trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='porcentaje_gestion',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=7),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='porcentaje_irpf',
            field=models.DecimalField(decimal_places=4, default=8, max_digits=7),
        ),
    ]
