# Generated by Django 4.2.16 on 2026-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_honorarios_and_remove_other_percentages'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='honorario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Honorario artista (%)'),
        ),
    ]
