# Generated by Django 4.2.16 on 2026-06-16 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_artist_honorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='at_ep_empresa',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.5'), max_digits=7, verbose_name='AT y EP empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='contingencias_comunes_empresa',
            field=models.DecimalField(decimal_places=4, default=Decimal('23.6'), max_digits=7, verbose_name='Contingencias comunes empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='contingencias_comunes_trabajador',
            field=models.DecimalField(decimal_places=4, default=Decimal('4.7'), max_digits=7, verbose_name='Contingencias comunes trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='desempleo_empresa',
            field=models.DecimalField(decimal_places=4, default=Decimal('6'), max_digits=7, verbose_name='Desempleo empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='desempleo_trabajador',
            field=models.DecimalField(decimal_places=4, default=Decimal('2'), max_digits=7, verbose_name='Desempleo trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='fogasa_empresa',
            field=models.DecimalField(decimal_places=4, default=Decimal('3'), max_digits=7, verbose_name='Fondo de garantía salarial empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='formacion_empresa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.6'), max_digits=7, verbose_name='Formación empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='formacion_trabajador',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1'), max_digits=7, verbose_name='Formación trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='mei_empresa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.75'), max_digits=7, verbose_name='MEI empresa'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='mei_trabajador',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=7, verbose_name='MEI trabajador'),
        ),
        migrations.AlterField(
            model_name='costpercentagesettings',
            name='porcentaje_honorarios',
            field=models.DecimalField(decimal_places=4, default=Decimal('5'), max_digits=7, verbose_name='Honorarios'),
        ),
    ]
