# Generated by Django 4.2.16 on 2026-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0020_artistrecord_lote_agrupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrecord',
            name='estado_seguridad_social',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Realizadas'), ('SENT', 'Enviadas'), ('CANCELLED', 'Canceladas')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupingrecordbatch',
            name='estado',
            field=models.CharField(choices=[('STANDBY', 'Presupuesto'), ('PROCESSED', 'Procesado')], default='STANDBY', max_length=20),
        ),
    ]
