# Generated by Django 4.2.16 on 2026-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0021_artistrecord_estado_seguridad_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrecord',
            name='estado_facturacion',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Realizadas'), ('COLLECTED', 'Cobradas'), ('PAID', 'Pagadas')], default='PENDING', max_length=20),
        ),
    ]
